import pandas as pd

# Load dataset generated by Java
data = pd.read_csv("result.csv")

print("\nLoaded Data:")
print(data)

# Convert attack result to numeric form
# 0 = Vulnerable (RSA)
# 1 = Quantum Safe (PQC)

data["AttackLabel"] = data["AttackResult"].apply(
    lambda x: 0 if "BROKEN" in x else 1
)

print("\nProcessed Data:")
print(data)

# Show dataset summary
print("\nDataset Information:")
print(data.info())

print("\nStatistical Summary:")
print(data.describe())

# Save processed dataset for next stages
data.to_csv("processed_dataset.csv", index=False)

print("\nProcessed dataset saved as processed_dataset.csv")