import pandas as pd

# Load CSV generated by Java
data = pd.read_csv(
    "results.csv",
    header=None,
    names=["Algorithm", "KeySize", "EncryptionTime", "AttackResult"]
)

print("\nLoaded Data:")
print(data)

# Convert attack result to numeric form
data["AttackLabel"] = data["AttackResult"].apply(
    lambda x: 0 if "BROKEN" in x else 1
)

print("\nProcessed Data:")
print(data)
